main:
  - name: Bio
    url: /about/
    weight: 10

  - name: Research
    url: /research/
    weight: 20

  - name: Publications
    url: /publications/
    weight: 30

  - name: Presentations
    url: /events/
    weight: 40

  - name: CV
    url: /cv/
    weight: 50
