name: Build CV

on:
  push:
    paths:
      - '/assets/cv/**'
      - '.github/workflows/build-cv.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: CV.tex
          working_directory: cv

      - name: Commit updated PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically update CV.pdf"
